# Generated by Django 5.2.17 on 2026-09-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='quests/'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='traders/'),
        ),
    ]
