# Generated by Django 5.2.17 on 2026-10-05 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_submission_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='dollars_reward',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Награда: доллары'),
        ),
        migrations.AddField(
            model_name='quest',
            name='euros_reward',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Награда: евро'),
        ),
        migrations.AddField(
            model_name='quest',
            name='experience_reward',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Награда: опыт'),
        ),
        migrations.AddField(
            model_name='quest',
            name='reputation_reward',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Награда: репутация'),
        ),
        migrations.AddField(
            model_name='quest',
            name='rewards_granted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='rubles_reward',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Награда: рубли'),
        ),
        migrations.AddField(
            model_name='trader',
            name='reputation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Текущая репутация'),
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(default='Игрок', max_length=100, verbose_name='Никнейм')),
                ('avatar', models.ImageField(blank=True, max_length=255, upload_to='players/', verbose_name='Аватар')),
                ('rubles', models.PositiveBigIntegerField(default=0, verbose_name='Рубли')),
                ('euros', models.PositiveBigIntegerField(default=0, verbose_name='Евро')),
                ('dollars', models.PositiveBigIntegerField(default=0, verbose_name='Доллары')),
                ('experience', models.PositiveBigIntegerField(default=0, verbose_name='Опыт')),
                ('experience_per_level', models.PositiveIntegerField(default=10000, help_text='Уровень = 1 + целая часть (опыт / опыт на уровень).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Опыт на уровень')),
            ],
            options={
                'verbose_name': 'Профиль игрока',
                'verbose_name_plural': 'Профиль игрока',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='single_player_profile')],
            },
        ),
    ]
